# Generated by Django 3.2.9 on 2021-12-22 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levelupapi', '0003_alter_event_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gametype',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='game',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
