# Generated by Django 3.2.9 on 2021-12-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20211222_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_by',
            new_name='gamer',
        ),
    ]
